"""The DOCX body style is 13pt / 1.25 / justified — asserted on the SHIPPED binary.

Why this file exists: the export's typography does not live in Python at runtime.
Pandoc reads `engine/examples/custom-reference.docx` via --reference-doc
(engine/utils/export_professional.py:1260,1277), and that .docx is a binary
generated by hand from create_reference_doc.py. Editing the script changes
nothing until someone re-runs it, and nothing in the repo noticed if they
didn't — there was no test of export formatting at all. So these assertions run
against the binary, not the script.

The last test closes the other half of the trap: it regenerates the document
from the current script and compares, so script and shipped binary cannot drift.
"""
from pathlib import Path

import pytest

docx = pytest.importorskip("docx")
from docx import Document  # noqa: E402
from docx.enum.text import WD_ALIGN_PARAGRAPH  # noqa: E402
from docx.shared import Pt  # noqa: E402

REFERENCE_DOC = (Path(__file__).resolve().parents[1]
                 / "engine" / "examples" / "custom-reference.docx")

# Body typography, as requested by the product owner 2026-08-20.
BODY_SIZE = Pt(13)
BODY_LINE_SPACING = 1.25
# Headings scale with the body: at 13pt body, the old H2/H3 of 12pt rendered
# SMALLER than the text they head.
HEADING_SIZES = {"Heading 1": Pt(16), "Heading 2": Pt(14), "Heading 3": Pt(13)}


@pytest.fixture(scope="module")
def reference() -> Document:
    assert REFERENCE_DOC.exists(), f"missing reference doc: {REFERENCE_DOC}"
    return Document(str(REFERENCE_DOC))


def test_body_is_13pt_justified_at_1_25(reference):
    normal = reference.styles["Normal"]
    assert normal.font.size == BODY_SIZE
    assert normal.paragraph_format.line_spacing == BODY_LINE_SPACING
    assert normal.paragraph_format.alignment == WD_ALIGN_PARAGRAPH.JUSTIFY


def test_body_font_family_is_unchanged(reference):
    # Only size/spacing/alignment were in scope; a font swap here would be an
    # unrequested change to every thesis this product ships.
    assert reference.styles["Normal"].font.name == "Times New Roman"


@pytest.mark.parametrize("style_name,expected", sorted(HEADING_SIZES.items()))
def test_headings_are_larger_than_the_body(reference, style_name, expected):
    style = reference.styles[style_name]
    assert style.font.size == expected
    assert style.font.size >= BODY_SIZE, "a heading must not be smaller than body text"


@pytest.mark.parametrize("style_name", sorted(HEADING_SIZES))
def test_headings_are_not_justified(reference, style_name):
    # Justification is for running prose. A justified heading stretches a short
    # line across the page and reads as a layout bug.
    assert reference.styles[style_name].paragraph_format.alignment != \
        WD_ALIGN_PARAGRAPH.JUSTIFY


@pytest.mark.parametrize("style_name", ["Normal", "Heading 1", "Heading 2",
                                        "Heading 3", "Block Text",
                                        "List Bullet", "List Number"])
def test_no_style_is_left_double_spaced(reference, style_name):
    # Mixed spacing is what makes a converted document look assembled rather
    # than written: body at 1.25 under headings still at 2.0.
    spacing = reference.styles[style_name].paragraph_format.line_spacing
    assert spacing == BODY_LINE_SPACING, f"{style_name} is at {spacing}"


def test_shipped_binary_matches_the_generator_script(tmp_path, monkeypatch):
    """Regenerating from the script must reproduce the shipped styles.

    This is the drift guard: create_reference_doc.py is the readable source of
    truth, custom-reference.docx is what pandoc actually consumes, and only a
    human re-running the script keeps them equal.
    """
    import sys
    sys.path.insert(0, str(REFERENCE_DOC.parent))
    import create_reference_doc  # type: ignore[import-not-found]

    monkeypatch.setattr(create_reference_doc, "Path", Path)
    generated_path = tmp_path / "custom-reference.docx"
    monkeypatch.setattr(create_reference_doc, "__file__",
                        str(tmp_path / "create_reference_doc.py"))
    create_reference_doc.create_reference_document()

    generated = Document(str(generated_path))
    shipped = Document(str(REFERENCE_DOC))
    for name in ["Normal", *HEADING_SIZES]:
        gen_pf = generated.styles[name].paragraph_format
        ship_pf = shipped.styles[name].paragraph_format
        assert generated.styles[name].font.size == shipped.styles[name].font.size, name
        assert gen_pf.line_spacing == ship_pf.line_spacing, name
        assert gen_pf.alignment == ship_pf.alignment, name
